tap 'cloudfoundry/tap'
tap 'universal-ctags/universal-ctags'
tap 'businesscritical/tap'

brew 'ack'
brew 'aria2'
brew 'awscli'
brew 'cloudfoundry/tap/bosh-cli'
brew 'cf-cli'
brew 'consul'
brew 'cloudfoundry/tap/credhub-cli'
brew 'direnv'
brew 'dishy'
brew 'fasd'
brew 'git-secrets'
brew 'jq'
brew 'node'
brew 'pstree'
brew 'qt'
brew 's3cmd'
brew 'ssh-copy-id'
brew 'tig'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'universal-ctags/universal-ctags/universal-ctags', args: ['HEAD']
brew 'watch'
brew 'wget'

cask 'flycut'
cask 'google-chrome'
cask 'slack'
cask 'spectacle'
