resources:
- name: capi-workspace
  type: git
  source:
    branch: new-workstations
    uri: https://github.com/cloudfoundry/capi-workspace

jobs:
  - name: create-latest-workstation
    plan:
    - get: capi-workspace
    - task: create-workstation-image
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: google/cloud-sdk
        params:
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))
          PCF_BOSH_LITE_DEPLOY_KEY: ((pcf_bosh_lite_pool_deploy_key))
        inputs:
        - name: capi-workspace
        run:
          path: bash
          args:
            - -c
            - |
              set -e
              gcloud auth activate-service-account --key-file=<(echo $GCP_SERVICE_ACCOUNT_KEY)
              echo "Creating Latest VM"
              gcloud compute instances create capi-ws-vm-latest --zone "us-central1-a" --project "cf-capi-arya" --boot-disk-size=50GB --boot-disk-type=pd-balanced --machine-type=e2-standard-8 --tags=workstations --image-family=ubuntu-2204-lts --image-project=ubuntu-os-cloud
              echo "wait 30 for instance to be up"
              sleep 30
              echo "copy capi-workspace over"
              gcloud compute ssh --zone "us-central1-a" "pivotal@capi-ws-vm-latest" --project "cf-capi-arya" -q --command 'mkdir -p ~/workspace'
              gcloud compute scp --recurse capi-workspace/ --zone "us-central1-a" "pivotal@capi-ws-vm-latest:~/workspace" --project "cf-capi-arya" -q
              echo "run set-up-new-machine.sh on workstation"
              eval `ssh-agent -s`
              ssh-add <(echo $PCF_BOSH_LITE_DEPLOY_KEY)
              gcloud compute ssh --zone "us-central1-a" "pivotal@capi-ws-vm-latest" --project "cf-capi-arya" -q --command 'ssh-keyscan github.com >> ~/.ssh/known_hosts'
              gcloud compute ssh --zone "us-central1-a" "pivotal@capi-ws-vm-latest" --project "cf-capi-arya" -q --command 'ssh-keyscan -t rsa github.com | ssh-keygen -lf -'
              gcloud compute ssh --zone "us-central1-a" "pivotal@capi-ws-vm-latest" --project "cf-capi-arya" -q --command '~/workspace/capi-workspace/set-up-new-machine.sh' --ssh-flag="-A"

              # if we don't wait, the last written file in the set up new machine script won't be written correctly when we make the machine image
              sleep 30

              gcloud compute machine-images describe capi-ws-image-latest --project "cf-capi-arya"
              testVal=$?
              if [[ $testVal -eq 0 ]]; then
                  echo "Delete old capi-ws-image-latest"
                  gcloud compute machine-images delete capi-ws-image-latest --project "cf-capi-arya" -q
              fi

              echo "Create source image from vm - 'capi-ws-image-latest' "
              gcloud compute machine-images create capi-ws-image-latest  --project "cf-capi-arya" --source-instance "capi-ws-vm-latest" --source-instance-zone "us-central1-a"
              echo "Let's delete the source vm instance - use base image to create a workstation"
              gcloud compute instances delete capi-ws-vm-latest --zone "us-central1-a" --project "cf-capi-arya" -q
              echo "you should probably check to see if this worked now, it probably did!"
              echo "try creating your own workstation vm from this image with: gcloud compute instances create capi-ws-yourname --zone 'us-central1-a' --source-machine-image 'capi-ws-image-latest'"
              echo "connect with, gcloud compute ssh --zone 'us-central1-a' 'pivotal@capi-ws-yourname' --project 'cf-capi-arya' --ssh-flag='-A'"
