#!/usr/bin/env ruby

require 'plist'

class Link
  def initialize(title, url)
    @title = title
    @url = url
  end

  def to_apple_hash
    {'ReadingListNonSync' =>
      {'neverFetchMetadata' => false},
      'URIDictionary' =>
        {'title' => @title},
      'URLString' => @url,
      'WebBookmarkType' => 'WebBookmarkTypeLeaf',
      'previewText' => '',
      'previewTextIsUserDefined' => true}
  end
end

bookmarks_plist_path = File.join('/Users', 'pivotal', 'Library', 'Safari', 'Bookmarks.plist')
bookmarks = Plist.parse_xml(`plutil -convert xml1 -o - #{bookmarks_plist_path}`)
folder_names = bookmarks['Children'].collect {|b| b['Title']}

index = if folder_names.include? 'CAPI'
          capi_folder_index = folder_names.find_index {|f| f == 'CAPI'}
          capi_folder = bookmarks['Children'][capi_folder_index]
          capi_folder['Children'] = []
          capi_folder_index
        else
          bookmarks['Children'].push(
            { 'Title' => 'CAPI',
              'WebBookmarkType' => 'WebBookmarkTypeList',
              'Children' => []
            })
          bookmarks['Children'].count - 1
        end

capi_folder = bookmarks['Children'][index]
capi_folder_links = capi_folder['Children']

{
  'CAPI Trello' => 'http://board.capi.land',
  'Chris' => 'http://chris.capi.land',
  'Elena' =>'http://elena.capi.land',
  'Greg' => 'http://greg.capi.land',
  'Mike' => 'http://mike.capi.land',
  'Tim' => 'http://tim.capi.land',
  'Video' =>'http://video.capi.land'
}.each do |name, url|
  capi_folder_links.push(Link.new(name, url).to_apple_hash)
end

File.open(bookmarks_plist_path, 'w') {|f| f.write bookmarks.to_plist}

`open -a "Safari"`
sleep 2
`osascript -e 'quit app "Safari"'`
