#!/usr/bin/env bash

ARG=$(echo $1 | awk '{print tolower($1)}')

if [ "$ARG" = "no" ]
then
    printf "Setting can-i-push to \e[1;31mNO\e[0m...\n"
    curl -X PUT "canibump.cfapps.io/$ARG" -d "token=maybe" -d "buildnumber=0"
    if [ $? -ne 0 ]
    then
        printf "\e[1;31mFAILED\e[0m\n"
        exit 1
    fi
    printf "can-i-push is now \e[1;31mNO\e[0m\n"
elif [ "$ARG" = "yes" ]
then
    printf "Setting can-i-push to \e[1;32mYES\e[0m\n"
    curl -X PUT "canibump.cfapps.io/$ARG" -d "token=maybe" -d "buildnumber=0"
    if [ $? -ne 0 ]
    then
        printf "\e[1;31mFAILED\e[0m\n"
        exit 1
    fi
    printf "can-i-push is now \e[1;32mYES\e[0m\n"
else
    YES=$(curl canibump.cfapps.io -s -H "Accept: application/json" | grep true)
    if [ "$YES" ]
    then
        printf "\e[1;32m%s\e[0m\n" "YES"
    else
        printf "\e[1;31m%s\e[0m\n" "NO"
        exit 1
    fi
fi
tput sgr0
