#!/usr/bin/env bash

set -e

cd ~/go/src/github.com/cloudfoundry/cf-acceptance-tests
FLAGS=$(cf feature-flags  | awk '/disabled/ { print $1 }')
if [[ -n "${FLAGS}" ]] ; then
  echo "The following feature-flags are disabled!:"
  echo "${FLAGS}"
  echo
  echo -n "Would you like them all enabled? (y/N): "
  read x
  case $x in
    [yY]*) echo ${FLAGS} | xargs -n 1 cf enable-feature-flag ;;
  esac
fi

if [[ -n ${CONFIG} && -f ${CONFIG} ]] ; then
    echo "Use CONFIG of ${CONFIG}"
else
    export CONFIG=${PWD}/integration_config.json
fi

bin/test --nodes=4
