#!/usr/bin/env bash

set -e

get_cf_admin_password() {
  echo "Getting CF admin password from credhub... "

  # Newer bosh-lites use $CREDHUB_SECRET instead of $CREDHUB_PASSWORD
  # The credhub cli is aware of $CREDHUB_SECRET so it does not need it passed in
  # If there are no bosh-lites around anymore that were created before 01/25/2018
  # you can delete the else condition
  set +u # $CREDHUB_PASSWORD may be unbound
  if [[ -z $CREDHUB_PASSWORD ]]; then
    credhub login --skip-tls-validation
  else
    credhub login -s "$CREDHUB_SERVER" -u "$CREDHUB_USERNAME" -p "$CREDHUB_PASSWORD" --skip-tls-validation
  fi
  set -u
  cf_admin_password=$(credhub get --name '/bosh-lite/cf/cf_admin_password' --output-json | jq -r '.value')
}

main() {
  if [ -z "$BOSH_ENVIRONMENT" ]; then
    echo "No bosh targeted. Use \"target_bosh\" before getting credhub password"
  else
    get_cf_admin_password
    echo "CF Admin Password: ${cf_admin_password}"
  fi
}

main
