#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -lt 1 ]; then
  echo "plz give your cluster a name"
  exit 1
fi
CLUSTER_NAME="${1}-cluster-1"

CURRENT_GCP_PROJECT="$(gcloud config get-value project)"
if [ $CURRENT_GCP_PROJECT != "cf-capi-arya" ]; then
  echo "FYI: you're currently targeting a different GCP project than where your cluster will be created"
fi

gcloud container clusters create "${CLUSTER_NAME}" \
  --cluster-version="1.14.10-gke.22" \
  --machine-type=n1-standard-2 \
  --num-nodes=5 \
  --zone us-central1-a \
  --project=cf-capi-arya

