#!/usr/bin/env bash

# you provide your own capi-release directory via the first positional argument
if [[ -n "$1" ]] ; then
  CAPI_RELEASE_DIR="$1" ; shift
else
  CAPI_RELEASE_DIR="$HOME/workspace/capi-release"
fi

bosh -n deploy <(bosh manifest) \
  -o ~/workspace/capi-ci/cf-deployment-operations/use-created-capi.yml \
  -o ~/workspace/capi-ci/cf-deployment-operations/increase-route-registration-interval.yml \
  -v capi_release_dir="${CAPI_RELEASE_DIR}" \
  --no-redact \
  "$@"
