#!/bin/bash

set -e

echo "Pulling 'capi-ci-private'..."
pushd ~/workspace/capi-ci-private > /dev/null
  git pull -r
popd > /dev/null

if ! fly -t capi status ; then
  fly -t capi login -b
fi

fly -t capi \
    set-pipeline \
    -p capi \
    -c ~/workspace/capi-ci/ci/pipeline.yml \
    -l ~/workspace/capi-ci-private/ci/credentials.yml
