#!/usr/bin/env bash


get_stories() {
	story_json="$(curl -s -H "Content-Type: application/json" \
	  "https://www.pivotaltracker.com/services/v5/projects/$project_id/stories?with_state=started" | tr '**' ' ')"
	echo $story_json | tr '\n' ' ' | jq '.[] | "#\(.id) \(.name)"'
	echo "No story"
	
}

story_selector() {
  stories="$(get_stories | sed 's/#//g')"

  PS3="Select a story or 'q' to quit: "
  OLD_IFS=$IFS
  IFS=$'\n'
  select story in $stories; do
    echo "$story"
    break
  done
  IFS=$OLD_IFS
}

story() {
    project_id=2196383

    story_selection="$(story_selector)"
    story_id="$(echo "$story_selection" | awk '{print $1;}' | sed s/\"//)"

    if [[ "$story_selection" == "No story" ]]; then
        echo "Unsetting current story."
        export STORY_NUM=''
        return
    fi

    STORY_TITLE="$(curl -s "https://www.pivotaltracker.com/services/v5/projects/${project_id}/stories/${story_id}" | jq -r .name)";
    STORY_URL="$(curl -s "https://www.pivotaltracker.com/services/v5/projects/${project_id}/stories/${story_id}" | jq -r .url)";

    export STORY_NUM="#${story_id} [${STORY_TITLE}](${STORY_URL})"

    # reset commit message now to include story
    git author $(git config git-together.active | sed -e 's/+/ /g')
}

story